services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/data

  test-postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/18/data

volumes:
  postgres_test_data:
  postgres_data:
