services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic

  postgres-test:
    image: postgres:17
    container_name: app-postgres-test
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/

volumes:
  postgres_test_data:
  postgres_data: